--- 
- hosts: 172.31.17.233 
  become: yes
  tasks: 
  - name: install git 
    apt:
      name: git 
      state: present 
    tags: mygit

  - name: install tree  
    apt:
      name: tree  
      stateeeee: present
    tags: mytree 
    ignore_errors: yes 

  - name: install wget 
    apt:
      name: wget 
      state: present 
    tags: mywget