--- 
- hosts: all 
  become: yes
  tasks: 
   - name: i want to install webserver on ansible ubuntu node
     apt: 
       name: apache2
       state: present  
   - name: i want tto start webserveron ansible ubuntu node 
     service:
      name: apache2 
      state: started   